In [66]:
import pandas as pd
from numpy import mean
from numpy import std
from matplotlib import pyplot
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score

In [67]:
dataset = pd.read_csv('Public Service/DKI Jakarta/Transportasi/agustus-2019-data-kecepatan-rata-rata-di-41-koridor-jalan-utama-pada-jam-sibuk.csv')

In [68]:
data = dataset.drop(['waktu', 'arah', 'koridor', 'target_kecepatan'],axis=1)
data

jarak  target_waktu_tempuh  pencapaian_kecepatan_per_koridor  \
0   19.62                56.06                             22.77   
1   13.36                38.17                             24.14   
2   11.13                31.80                             29.64   
3   16.25                46.43                             25.82   
4   15.87                45.34                             28.18   
..    ...                  ...                               ...   
77  20.29                57.97                             21.01   
78  14.47                41.34                             20.41   
79  15.55                44.43                             17.41   
80  17.43                49.80                             22.10   
81  16.23                46.37                             21.08   

    pencapaian_kecepatan  pencapaian_waktu_tempuh  
0                  24.36                    58.82  
1                  24.36                    36.88  
2                  24.36                    25.99  
3                  24.36                    44.35  
4                  24.36                    37.33  
..                   ...                      ...  
77                 23.46                    58.78  
78                 20.25                    45.81  
79                 20.25                    56.99  
80                 20.25                    54.92  
81                 20.25                    52.68  

[82 rows x 5 columns]

In [69]:
# ordinal encoder

In [70]:
new_data = data.values[:, :-1]
X = new_data[:, :4]
y = new_data[:, [-1]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
ordinal_encoder = OrdinalEncoder()
X_train = ordinal_encoder.fit_transform(X_train)
X_test = ordinal_encoder.fit_transform(X_test)
# ordinal encode target variable
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.fit_transform(y_test)
X_train

c:\users\moody asyer\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([[11., 11., 25.,  9.],
       [ 8.,  8., 33.,  5.],
       [26., 26.,  4.,  0.],
       [10., 10., 14., 10.],
       [29., 29., 11.,  1.],
       [ 3.,  3., 39.,  9.],
       [18., 18., 43., 12.],
       [22., 22., 27., 13.],
       [35., 35., 21., 10.],
       [22., 22.,  2.,  1.],
       [25., 25., 30.,  7.],
       [34., 34., 19.,  4.],
       [16., 16.,  9.,  4.],
       [25., 25., 24.,  9.],
       [32., 32., 42., 11.],
       [27., 27., 20., 10.],
       [36., 36.,  8.,  3.],
       [14., 14., 23.,  8.],
       [33., 33., 13.,  7.],
       [15., 15.,  1.,  5.],
       [ 9.,  9., 10.,  4.],
       [28., 28., 18.,  3.],
       [17., 17.,  5.,  1.],
       [14., 14., 40., 12.],
       [ 7.,  7., 15.,  6.],
       [13., 13., 37., 10.],
       [15., 15., 40., 14.],
       [21., 21., 41., 15.],
       [ 5.,  5., 26.,  4.],
       [36., 36., 44., 11.],
       [33., 33., 28.,  9.],
       [19., 19., 45., 12.],
       [ 2.,  2., 49., 10.],
       [24., 24., 38.,  7.],
       [31., 3

In [71]:
X_test

array([[13., 13.,  2.,  3.],
       [ 0.,  0.,  9.,  0.],
       [ 8.,  8., 16.,  9.],
       [ 4.,  4., 11.,  4.],
       [16., 16., 19., 12.],
       [18., 18.,  1.,  2.],
       [12., 12., 15., 11.],
       [16., 16.,  5.,  1.],
       [22., 22.,  4.,  5.],
       [15., 15., 22.,  9.],
       [ 6.,  6., 12.,  5.],
       [14., 14.,  6.,  2.],
       [19., 19., 18., 10.],
       [22., 22., 13., 13.],
       [ 9.,  9.,  8.,  2.],
       [17., 17., 17., 14.],
       [ 6.,  6., 23., 13.],
       [21., 21., 27., 14.],
       [13., 13., 21., 10.],
       [20., 20., 24., 12.],
       [ 1.,  1., 20.,  7.],
       [ 5.,  5., 25., 13.],
       [ 2.,  2., 26., 13.],
       [ 3.,  3., 10.,  9.],
       [10., 10.,  7.,  6.],
       [ 7.,  7.,  0.,  2.],
       [23., 23.,  3.,  2.],
       [11., 11., 14.,  8.]])

In [72]:
y_train

array([ 9,  5,  0, 10,  1,  9, 12, 13, 10,  1,  7,  4,  4,  9, 11, 10,  3,
        8,  7,  5,  4,  3,  1, 12,  6, 10, 14, 15,  4, 11,  9, 12, 10,  7,
        0,  6, 15, 15,  3,  8,  8, 11, 10,  7,  0,  7,  6,  2,  7,  5,  3,
        0,  6, 13], dtype=int64)

In [73]:
y_test

array([ 3,  0,  9,  4, 12,  2, 11,  1,  5,  9,  5,  2, 10, 13,  2, 14, 13,
       14, 10, 12,  7, 13, 13,  9,  6,  2,  2,  8], dtype=int64)

In [74]:
model = RandomForestRegressor()
cv = KFold(n_splits=10)
n_scores = cross_val_score(model, X_train, y_train, scoring = 'r2', cv = cv, n_jobs= -1)
print('Accuracy: %.5f (%.5f)' % (mean(n_scores)*100, std(n_scores)))

Accuracy: 98.95159 (0.00957)


In [75]:
# one-hot encoder
new_data_1 = data.values[:, :-1]
X_1 = new_data_1[:, :4]
y_1 = new_data_1[:, [-1]]
X_train, X_test, y_train, y_test = train_test_split(X_1, y_1, test_size=0.33, random_state=1)
oneHot_encoder = OneHotEncoder()
X_train = oneHot_encoder.fit_transform(X_train)
X_test = oneHot_encoder.fit_transform(X_test)
# one-hot encoder target variable
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.fit_transform(y_test)
X_train

c:\users\moody asyer\appdata\local\programs\python\python39\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


<54x142 sparse matrix of type '<class 'numpy.float64'>'
	with 216 stored elements in Compressed Sparse Row format>

In [76]:
X_test

<28x91 sparse matrix of type '<class 'numpy.float64'>'
	with 112 stored elements in Compressed Sparse Row format>

In [77]:
y_train

array([ 9,  5,  0, 10,  1,  9, 12, 13, 10,  1,  7,  4,  4,  9, 11, 10,  3,
        8,  7,  5,  4,  3,  1, 12,  6, 10, 14, 15,  4, 11,  9, 12, 10,  7,
        0,  6, 15, 15,  3,  8,  8, 11, 10,  7,  0,  7,  6,  2,  7,  5,  3,
        0,  6, 13], dtype=int64)

In [78]:
y_test

array([ 3,  0,  9,  4, 12,  2, 11,  1,  5,  9,  5,  2, 10, 13,  2, 14, 13,
       14, 10, 12,  7, 13, 13,  9,  6,  2,  2,  8], dtype=int64)

In [79]:
model = RandomForestRegressor()
cv = KFold(n_splits=10)
n_scores = cross_val_score(model, X_train, y_train, scoring = 'r2', cv = cv, n_jobs= -1)
print('Accuracy: %.5f (%.5f)' % (mean(n_scores)*100, std(n_scores)))

Accuracy: 54.33122 (0.33844)
